//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_serivces
    {
        public int id { get; set; }
        public Nullable<int> idService { get; set; }
        public Nullable<int> idBooking { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual service service { get; set; }
    }
}
