//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public booking()
        {
            this.booking_serivces = new HashSet<booking_serivces>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> checkIn { get; set; }
        public Nullable<System.DateTime> checkOut { get; set; }
        public Nullable<int> idRoom { get; set; }
        public Nullable<int> numberBookedRooms { get; set; }
        public Nullable<int> numberOfPeople { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> idUser { get; set; }
        public string recordStatus { get; set; }
        public string paid { get; set; }
    
        public virtual account account { get; set; }
        public virtual room room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_serivces> booking_serivces { get; set; }
    }
}
