//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer
    {
        public int id { get; set; }
        public Nullable<int> nrBookedRooms { get; set; }
        public Nullable<int> newPrice { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public string recordStatus { get; set; }
        public string offerName { get; set; }
    }
}
